esphome:
  name: ac-controller
  includes:
    - electra_ir.h
  libraries:
    - IRremoteESP8266

ota:

api:

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

logger:
  level: VERBOSE
  baud_rate: 0

remote_transmitter:
  pin: GPIO17
  carrier_duty_percent: 50%

remote_receiver:
  pin: GPIO16
  dump: all
  # Consider listening for messages from original remote and applying those into the state?
  # on_raw: |-

sensor:
  - platform: homeassistant
    id: current_temperature
    entity_id: sensor.olohuone_temperature_calibrated

climate:
  platform: custom
  lambda: |-
    auto bedroom_ac = new ElectraAc(id(current_temperature));
    App.register_component(bedroom_ac);
    return {bedroom_ac};

  climates:
    - name: "Olohuone AC"
